# yaml-language-server: $schema=../../../../configuration-schema.json
package: api
generate:
  chi-server: true
  models: true
  embedded-spec: true
compatibility:
  apply-chi-middleware-first-to-last: true
output: nimbus_openapi.gen.go
